flag msg in shop (same way as for bank)
DDNetPP/DDNetPP pull request #157
Opened 2018-10-04 19:06 UTC by fokkonaut

2018-10-04 19:53 UTC, ChillerDragon requested changes

2018-10-04 19:53 UTC, ChillerDragon commented on src/game/server/entities/character.cpp
> +					dbg_msg("debug", "shoptile");
remove debug messages pls

2018-10-04 19:53 UTC, ChillerDragon commented on src/game/server/entities/character.cpp
> +				dbg_msg("debug", "shoptile");
here aswell

2018-10-04 19:54 UTC, fokkonaut commented on src/game/server/entities/character.cpp
> +				dbg_msg("debug", "shoptile");
no u made it too

2018-10-04 20:36 UTC, fokkonaut commented
merge

2018-10-05 21:27 UTC, ChillerDragon approved these changes

2018-10-05 21:27 UTC, merged